### ISSUE TITLE
Supports slashes in dates

### ISSUE THREAD

**Issue by michielbdejong** [kajyr/pta-tools#5]
Looking at for instance [this sample from the hledger repo](https://github.com/simonmichael/hledger/blob/master/examples/sample.journal), dates can be formatted as `2008/12/31` instead of `2008-12-31` but the `parse` function doesn't accept those

**Comment by kajyr** [comment]
Yep, I think that there are a good number of things that are not implemented yet, from the basic hledger syntax. But It's good to improve :)
